<template>
    <div class="p-6">
      <h1 class="text-2xl font-bold mb-4 text-gray-800">Reports</h1>
      
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div class="bg-white p-4 rounded-lg shadow">
          <h2 class="text-lg font-medium text-gray-800 mb-4">Monthly Sales</h2>
          <div class="h-64 bg-gray-100 rounded flex items-center justify-center">
            <p class="text-gray-500">Sales Chart Placeholder</p>
          </div>
          <div class="mt-4 grid grid-cols-3 gap-4 text-center">
            <div>
              <p class="text-sm text-gray-500">This Month</p>
              <p class="text-lg font-medium text-gray-800">$24,500</p>
            </div>
            <div>
              <p class="text-sm text-gray-500">Last Month</p>
              <p class="text-lg font-medium text-gray-800">$22,700</p>
            </div>
            <div>
              <p class="text-sm text-gray-500">Change</p>
              <p class="text-lg font-medium text-green-600">+7.9%</p>
            </div>
          </div>
        </div>
        
        <div class="bg-white p-4 rounded-lg shadow">
          <h2 class="text-lg font-medium text-gray-800 mb-4">User Growth</h2>
          <div class="h-64 bg-gray-100 rounded flex items-center justify-center">
            <p class="text-gray-500">User Growth Chart Placeholder</p>
          </div>
          <div class="mt-4 grid grid-cols-3 gap-4 text-center">
            <div>
              <p class="text-sm text-gray-500">New Users</p>
              <p class="text-lg font-medium text-gray-800">843</p>
            </div>
            <div>
              <p class="text-sm text-gray-500">Total Users</p>
              <p class="text-lg font-medium text-gray-800">5,243</p>
            </div>
            <div>
              <p class="text-sm text-gray-500">Growth</p>
              <p class="text-lg font-medium text-green-600">+19.2%</p>
            </div>
          </div>
        </div>
      </div>
      
      <div class="mt-6 bg-white p-4 rounded-lg shadow">
        <div class="flex justify-between items-center mb-4">
          <h2 class="text-lg font-medium text-gray-800">Recent Reports</h2>
          <button class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">Generate New Report</button>
        </div>
        
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Report Name</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr v-for="report in reports" :key="report.id">
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm font-medium text-gray-900">{{ report.name }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{ report.generatedBy }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{ report.date }}</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                <a href="#" class="text-blue-600 hover:text-blue-900 mr-3">View</a>
                <a href="#" class="text-green-600 hover:text-green-900 mr-3">Download</a>
                <a href="#" class="text-red-600 hover:text-red-900">Delete</a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    name: 'ReportsView',
    data() {
      return {
        reports: [
          { id: 1, name: 'Monthly Sales Report - February', generatedBy: 'John Doe', date: '03/01/2025' },
          { id: 2, name: 'User Activity Q1', generatedBy: 'System', date: '02/28/2025' },
          { id: 3, name: 'Inventory Status', generatedBy: 'Jane Smith', date: '02/25/2025' },
          { id: 4, name: 'Marketing Campaign Performance', generatedBy: 'Marketing Team', date: '02/22/2025' },
          { id: 5, name: 'Customer Satisfaction Survey', generatedBy: 'Customer Support', date:  '02/22/2025' }
          ]
        }
    }
}
</script>
